language: node_js
node_js:
  - node

cache:
  npm: true
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm install -g codecov

script:
  - npm run test:coverage

after_success:
  - npm run codecov
